GetTerminus/terminus-github-actions

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/taskcomplete.yaml
CODEOWNERS

creating a PR template
declaring MInimal Risk within the PR template to meet change control procedures
adding/creating SRE ownership to CodeOwners
establishing task completer so checkboxes must be reviewed before merging

Creating CodeOwners File/Setting Minimal Risk/Placing Task Checks

---

multi-workspace-infra/terraform-plan/action.yaml

Add helm chart setup so we can run lint during plan

---

terraform-state-rm/action.yaml

no input flag for state rm

---

multi-workspace-infra/terraform-apply/action.yaml
multi-workspace-infra/terraform-plan/action.yaml

Add lfs feature

---

multi-workspace-infra/terraform-apply/action.yaml
multi-workspace-infra/terraform-plan/action.yaml

fix: initial_run

---

multi-workspace-infra/terraform-plan/action.yaml

fix: commenter workspace

---

single-workspace-infra/terraform-plan/action.yaml

fix: clean plan

---

multi-workspace-infra/terraform-plan/action.yaml

Commenter intermediate file

---

multi-workspace-infra/terraform-plan/action.yaml

Fix GHA build (needs ref)

---

multi-workspace-infra/terraform-apply/action.yaml
multi-workspace-infra/terraform-plan/action.yaml
single-workspace-infra/terraform-plan/action.yaml

Dpr fix directory bug

---

single-workspace-infra/terraform-plan/action.yaml

Fixing indentation on step

---

multi-workspace-infra/terraform-apply/action.yaml
multi-workspace-infra/terraform-deploy/action.yaml
multi-workspace-infra/terraform-plan/action.yaml
service-build/go-build/action.yaml
service-build/go-test/action.yaml
service-build/spark-build/action.yaml
service-build/spark-test/action.yaml
shell-scripts/input-validator.sh
single-workspace-infra/terraform-apply/action.yaml
single-workspace-infra/terraform-deploy-eks/action.yaml
single-workspace-infra/terraform-plan/action.yaml
terraform-import/action.yaml
terraform-state-rm/action.yaml
terraform-state-unlock/action.yaml

feat: add go service build and test

---

single-workspace-infra/terraform-plan/action.yaml

fix: hotfix

---

terraform-import/action.yaml
terraform-state-rm/action.yaml
terraform-state-unlock/action.yaml

fix: unlock

---

.github/workflows/release.yaml
.pre-commit-config.yaml

Dpr add auto tagger

---

.github/workflows/release-beta.yaml

Dpr add auto tagger beta

---

multi-workspace-infra/terraform-deploy/action.yaml

add environment as input variable

---

multi-workspace-infra/terraform-apply/action.yaml
multi-workspace-infra/terraform-plan/action.yaml
terraform-import/action.yaml

- Synthetic tests will now trigger as long as the tests are tagged with the service:${service_name} and the service name is a terraform output variable

feat: add dd synthetic test trigger to ci pipeline

---

multi-workspace-infra/terraform-apply/action.yaml

fix: dd synthetic test input default

---

multi-workspace-infra/terraform-plan/action.yaml
single-workspace-infra/terraform-plan/action.yaml
terraform-state-rm/action.yaml
terraform-state-unlock/action.yaml

feat: fix unlock and state rm

---

multi-workspace-infra/terraform-apply/action.yaml
multi-workspace-infra/terraform-plan/action.yaml

Auto get helm charts

---

multi-workspace-infra/terraform-apply/action.yaml

Adding step for running cypress integration tests.

feat: add step for cypress integration tests.

---

multi-workspace-infra/terraform-apply/action.yaml

fix: deliverybot

---

multi-workspace-infra/terraform-apply/action.yaml

fix: deliverybot v2

---

multi-workspace-infra/terraform-plan/action.yaml
single-workspace-infra/terraform-plan/action.yaml

PR commenter outputs

---

multi-workspace-infra/terraform-plan/action.yaml

Fix bash length

---

multi-workspace-infra/terraform-plan/action.yaml
single-workspace-infra/terraform-plan/action.yaml

Fix single workspace; fix diff syntax

---

multi-workspace-infra/terraform-plan/action.yaml
single-workspace-infra/terraform-plan/action.yaml

Fix blank fail comments again

---

terraform-import/action.yaml

fix: import

---

multi-workspace-infra/terraform-plan/action.yaml
single-workspace-infra/terraform-plan/action.yaml

feat: add commenter v1 version

---

terraform-state-replace-provider/action.yaml

Add action to replace provider

---

terraform-state-replace-provider/action.yaml

fix: provider issue

---

.github/workflows/release-beta.yaml
service-build/go-build-targets/action.yaml
service-build/go-build/action.yaml
service-build/go-test/action.yaml
shell-scripts/input-validator.sh

feat: refactor go build

---

single-workspace-infra/terraform-plan/action.yaml
terraform-import/action.yaml

fix: terraform_workspace
